// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1711353786);
user_pref("app.update.lastUpdateTime.background-update-timer", 1711353786);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1711353786);
user_pref("app.update.lastUpdateTime.region-update-timer", 1711353786);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1711353786);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1711353786);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.jxl", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1711353756);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migrate.interactions.bookmarks", true);
user_pref("browser.migrate.interactions.history", true);
user_pref("browser.migration.version", 137);
user_pref("browser.migration.waterfox_version", 1);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5a847a33-b519-4c9e-b7cc-57e14b474322}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1711353762);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1711353782654");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1711375382654");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.sidebar.permissionsGranted", true);
user_pref("browser.sidebar.simulateTabsLoadInBackgroundInverted", true);
user_pref("browser.sidebar.toolbarButtonInserted", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20240324110634");
user_pref("browser.startup.homepage_override.mstone", "115.10.0");
user_pref("browser.startup.lastColdStartupCheck", 1711353762);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"save-to-pocket-button\",\"search-container\",\"toggle-tabs-sidebar\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"status-bar\":[\"screenshot-button\",\"fullscreen-button\",\"status-text\"]},\"seen\":[\"developer-button\",\"toggle-tabs-sidebar\"],\"dirtyAreaCache\":[\"nav-bar\",\"status-bar\",\"PersonalToolbar\",\"TabsToolbar\"],\"currentVersion\":19,\"newElementCount\":3}");
user_pref("browser.urlbar.placeholderName", "Bing");
user_pref("distribution.iniFile.exists.appversion", "115.10.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "dc957e2a323047239a8603e704064ae9");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1711353787);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240324110634");
user_pref("extensions.lastAppVersion", "115.10.0");
user_pref("extensions.lastPlatformVersion", "115.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.quarantinedDomains.list", "autoatendimento.bb.com.br,ibpf.sicredi.com.br,ibpj.sicredi.com.br,internetbanking.caixa.gov.br,www.ib12.bradesco.com.br,www2.bancobrasil.com.br");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.sidebar@waterfox.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"70aebb83-dcf4-4757-9ab1-e87198dc02d1\",\"pictureinpicture@mozilla.org\":\"c6b5e906-0db4-46ac-974a-f9f67240fddd\",\"screenshots@mozilla.org\":\"56ad8c2b-1aad-4723-905d-015f6863fb47\",\"webcompat-reporter@mozilla.org\":\"2bb8a638-1382-4105-a63c-0758bbd1ee15\",\"webcompat@mozilla.org\":\"dc96c407-f438-445b-b7c1-fd10a36c93fe\",\"default-theme@mozilla.org\":\"daacaa7e-5f40-44ee-a2d1-ef9453e1845a\",\"addonstores@waterfox.net\":\"3bddc24a-06e5-495f-85f3-626845d1cfd3\",\"addons-search-detection@mozilla.com\":\"fbfdef04-5f1b-42da-8dd2-3f4c9cc8938e\",\"bing@search.waterfox.net\":\"2f9d4dfa-3548-4e0f-aeba-4dd46b3b7008\",\"sidebar@waterfox.net\":\"952223a2-4dd0-4d97-9820-bf6938795199\",\"startpage@search.waterfox.net\":\"182a43c4-0961-4509-b56e-f210e16ddd47\",\"yahoo@search.waterfox.net\":\"c9a5860d-3d38-43ff-9682-ba5acbd86c00\",\"google@search.waterfox.net\":\"cc125fb8-ed46-4b7e-8f21-c2ae79386847\",\"ddg@search.waterfox.net\":\"16783288-3ae2-4a59-bb82-ce527a66610a\",\"qwant@search.waterfox.net\":\"2d5668b9-fad7-4fe7-ad72-9403012b4bc5\",\"ecosia@search.waterfox.net\":\"7ae468d2-0f28-488b-88e0-b9c242c5132c\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "53a58bfb4c8124ad4f7655b99bfdea290033a085e0796b19245b33b91c0948fdac9f0c3e817130b352493a65d9a7a0fc8a7c1eedc618cdaa2b4580734a11cd9c");
user_pref("media.gmp-gmpopenh264.lastDownload", 1711353789);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1711353788);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1711353789);
user_pref("media.gmp-gmpopenh264.version", "2.3.2");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.globalprivacycontrol.was_ever_enabled", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "ab31b1c8-616b-45fb-a2ed-f2fba416dc5e");
user_pref("services.settings.blocklists.addons-bloomfilters.last_check", 1711353786);
user_pref("services.settings.blocklists.gfx.last_check", 1711353786);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1711339034422\"");
user_pref("services.settings.last_update_seconds", 1711353786);
user_pref("services.settings.main.addons-manager-settings.last_check", 1711353786);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1711353786);
user_pref("services.settings.main.cookie-banner-rules-list.last_check", 1711353786);
user_pref("services.settings.main.devtools-compatibility-browsers.last_check", 1711353786);
user_pref("services.settings.main.devtools-devices.last_check", 1711353786);
user_pref("services.settings.main.doh-config.last_check", 1711353786);
user_pref("services.settings.main.doh-providers.last_check", 1711353786);
user_pref("services.settings.main.hijack-blocklists.last_check", 1711353786);
user_pref("services.settings.main.language-dictionaries.last_check", 1711353786);
user_pref("services.settings.main.password-recipes.last_check", 1711353786);
user_pref("services.settings.main.password-rules.last_check", 1711353786);
user_pref("services.settings.main.pioneer-study-addons-v1.last_check", 1711353786);
user_pref("services.settings.main.search-config.last_check", 1711353786);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1711353786);
user_pref("services.settings.main.search-telemetry-v2.last_check", 1711353786);
user_pref("services.settings.main.sites-classification.last_check", 1711353786);
user_pref("services.settings.main.top-sites.last_check", 1711353786);
user_pref("services.settings.main.translations-models.last_check", 1711353786);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1711353786);
user_pref("services.settings.main.websites-with-shared-credential-backends.last_check", 1711353786);
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1711353755);
user_pref("toolkit.telemetry.cachedClientID", "c51d1827-493f-4407-ae3a-455d7fdab25b");
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
