github.com:
    users:
        Sinhran:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: Sinhran
