###############
### SOURCES ###
###############

# Environment
source = ~/.config/hypr/env.conf

# NVIDIA environment
source = ~/.local/share/dotfiles/default/hypr/conf/nvidia-env.conf

# Monitor config
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/input.conf

# Autostart
source = ~/.config/hypr/conf/autostart.conf

# Keybindings
source = ~/.config/hypr/conf/desktop-keybindings.conf

# Look and feel
source = ~/.config/hypr/conf/looknfeel.conf

# Window rules
source = ~/.config/hypr/conf/windowrules.conf

# Layer rules
source = ~/.config/hypr/conf/layerrules.conf
