#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Layout
yabai -m config layout float
# Window Settings
#yabai -m config window_placement first_child
#yabai -m config window_topmost off
#yabai -m config window_shadow on
#yabai -m config window_opacity on
#yabai -m config active_window_opacity 1.0
#yabai -m config normal_window_opacity 0.8
#yabai -m config auto_balance off
#yabai -m config split_ratio 0.50
#
## Padding for Sketchybar
yabai -m config external_bar all:37:0
## Padding 
yabai -m config bottom_padding 4
yabai -m config left_padding 4
yabai -m config right_padding 4
yabai -m config window_gap 8
#
## Mouse Interactions
yabai -m config focus_follows_mouse     autoraise
#yabai -m config mouse_modifier fn
#yabai -m config mouse_action2 resize
#yabai -m config mouse_action1 move
#
## general space settings
##yabai -m config focused_border_skip_floating 1
##yabai -m config --space 3 layout       float
#
## float system preferences. Most of these just diable Yabai form resizing them.
#yabai -m rule --add app="^System Settings$" manage=off layer=above
#yabai -m rule --add app="^Karabiner-Elements$" manage=off layer=above sticky=on
#yabai -m rule --add app="^Karabiner-EventViewer$" manage=off layer=above
#yabai -m rule --add app="^Stats$" manage=off layer=above
#yabai -m rule --add app="^Calculator$" manage=off layer=above
#yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
#yabai -m rule --add app="^Path Finder$" manage=off layer=above
## yabai -m rule --add app="^WhatPulse$" manage=off
## yabai -m rule --add app="^Disk Utility$" manage=off
## yabai -m rule --add app="^System Information$" manage=off
#yabai -m rule --add app="^Activity Monitor$" manage=off layer=above
#yabai -m rule --add app="Fantastical" manage=off layer=above
#yabai -m rule --add app="Calendar" manage=off layer=above
## yabai -m rule --add app="^Spotify$" manage=off
#yabai -m rule --add app="^Logi Options$" manage=off
## yabai -m rule --add app="^Mail$" manage=off
## yabai -m rule --add app="^LinearMouse$" manage=off
## yabai -m rule --add app="^DropPoint$" manage=off
#yabai -m rule --add app="^FaceTime$" manage=off layer=above
## yabai -m rule --add app="^Whatsapp$" manage=off
#yabai -m rule --add app="^coconutBattery$" manage=off
#
#yabai -m space 1 --label one
#yabai -m space 2 --label two
#yabai -m space 3 --label three
#yabai -m space 4 --label four
#yabai -m space 5 --label five
#yabai -m space 6 --label six
#yabai -m space 9 --label nine

# signals
# yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add event=space_changed action="yabai -m window --focus $(yabai -m query --windows --window | jq ".id")"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"


## If I close the active window, focus on any other visible window.
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

#This needs https://github.com/FelixKratz/JankyBorders
borders active_color=0xff05dffc inactive_color=0xfffc05e7 width=5.0 blacklist="Todoist" &
borders active_color=0xff05dffc inactive_color=0xfffc05e7 width=3.0 whitelist="kitty" &
echo "yabai configuration loaded.."

#END
