# ===== Pipewire =====
exec-once = pipewire
exec-once = pipewire-pulse
exec-once = wireplumber

# ===== Polkit =====
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# ===== Wallpaper =====
# exec-once = hyprpaper
exec-once = swww-daemon
exec-once = swww -i /home/engel/Pictures/makima.png

# ===== Notifications =====
exec-once = dunst

# ===== Idle =====
exec-once = hypridle

# ===== Waybar =====
exec-once = waybar
