[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "Iosevka Nerd Font Mono"
bold.family = "Iosevka Nerd Font Mono"
italic.family = "IosevkaTerm Nerd Font Mono"
bold_italic.family = "IosevkaTermSlab Nerd Font Mono"

size = 15.0
